# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/walle07

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/walle07

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/walle07/CMakeFiles /home/pi/walle07/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/walle07/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named walle

# Build rule for target.
walle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 walle
.PHONY : walle

# fast build rule for target.
walle/fast:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/build
.PHONY : walle/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/main.cpp.s
.PHONY : main.cpp.s

motor.o: motor.cpp.o

.PHONY : motor.o

# target to build an object file
motor.cpp.o:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/motor.cpp.o
.PHONY : motor.cpp.o

motor.i: motor.cpp.i

.PHONY : motor.i

# target to preprocess a source file
motor.cpp.i:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/motor.cpp.i
.PHONY : motor.cpp.i

motor.s: motor.cpp.s

.PHONY : motor.s

# target to generate assembly for a file
motor.cpp.s:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/motor.cpp.s
.PHONY : motor.cpp.s

robot.o: robot.cpp.o

.PHONY : robot.o

# target to build an object file
robot.cpp.o:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/robot.cpp.o
.PHONY : robot.cpp.o

robot.i: robot.cpp.i

.PHONY : robot.i

# target to preprocess a source file
robot.cpp.i:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/robot.cpp.i
.PHONY : robot.cpp.i

robot.s: robot.cpp.s

.PHONY : robot.s

# target to generate assembly for a file
robot.cpp.s:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/robot.cpp.s
.PHONY : robot.cpp.s

sensor.o: sensor.cpp.o

.PHONY : sensor.o

# target to build an object file
sensor.cpp.o:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/sensor.cpp.o
.PHONY : sensor.cpp.o

sensor.i: sensor.cpp.i

.PHONY : sensor.i

# target to preprocess a source file
sensor.cpp.i:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/sensor.cpp.i
.PHONY : sensor.cpp.i

sensor.s: sensor.cpp.s

.PHONY : sensor.s

# target to generate assembly for a file
sensor.cpp.s:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/sensor.cpp.s
.PHONY : sensor.cpp.s

utils/camera/camera.o: utils/camera/camera.cpp.o

.PHONY : utils/camera/camera.o

# target to build an object file
utils/camera/camera.cpp.o:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/camera/camera.cpp.o
.PHONY : utils/camera/camera.cpp.o

utils/camera/camera.i: utils/camera/camera.cpp.i

.PHONY : utils/camera/camera.i

# target to preprocess a source file
utils/camera/camera.cpp.i:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/camera/camera.cpp.i
.PHONY : utils/camera/camera.cpp.i

utils/camera/camera.s: utils/camera/camera.cpp.s

.PHONY : utils/camera/camera.s

# target to generate assembly for a file
utils/camera/camera.cpp.s:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/camera/camera.cpp.s
.PHONY : utils/camera/camera.cpp.s

utils/camera/cameracontrol.o: utils/camera/cameracontrol.cpp.o

.PHONY : utils/camera/cameracontrol.o

# target to build an object file
utils/camera/cameracontrol.cpp.o:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/camera/cameracontrol.cpp.o
.PHONY : utils/camera/cameracontrol.cpp.o

utils/camera/cameracontrol.i: utils/camera/cameracontrol.cpp.i

.PHONY : utils/camera/cameracontrol.i

# target to preprocess a source file
utils/camera/cameracontrol.cpp.i:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/camera/cameracontrol.cpp.i
.PHONY : utils/camera/cameracontrol.cpp.i

utils/camera/cameracontrol.s: utils/camera/cameracontrol.cpp.s

.PHONY : utils/camera/cameracontrol.s

# target to generate assembly for a file
utils/camera/cameracontrol.cpp.s:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/camera/cameracontrol.cpp.s
.PHONY : utils/camera/cameracontrol.cpp.s

utils/lib/HMC5883L.o: utils/lib/HMC5883L.cpp.o

.PHONY : utils/lib/HMC5883L.o

# target to build an object file
utils/lib/HMC5883L.cpp.o:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/lib/HMC5883L.cpp.o
.PHONY : utils/lib/HMC5883L.cpp.o

utils/lib/HMC5883L.i: utils/lib/HMC5883L.cpp.i

.PHONY : utils/lib/HMC5883L.i

# target to preprocess a source file
utils/lib/HMC5883L.cpp.i:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/lib/HMC5883L.cpp.i
.PHONY : utils/lib/HMC5883L.cpp.i

utils/lib/HMC5883L.s: utils/lib/HMC5883L.cpp.s

.PHONY : utils/lib/HMC5883L.s

# target to generate assembly for a file
utils/lib/HMC5883L.cpp.s:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/lib/HMC5883L.cpp.s
.PHONY : utils/lib/HMC5883L.cpp.s

utils/lib/I2Cdev.o: utils/lib/I2Cdev.cpp.o

.PHONY : utils/lib/I2Cdev.o

# target to build an object file
utils/lib/I2Cdev.cpp.o:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/lib/I2Cdev.cpp.o
.PHONY : utils/lib/I2Cdev.cpp.o

utils/lib/I2Cdev.i: utils/lib/I2Cdev.cpp.i

.PHONY : utils/lib/I2Cdev.i

# target to preprocess a source file
utils/lib/I2Cdev.cpp.i:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/lib/I2Cdev.cpp.i
.PHONY : utils/lib/I2Cdev.cpp.i

utils/lib/I2Cdev.s: utils/lib/I2Cdev.cpp.s

.PHONY : utils/lib/I2Cdev.s

# target to generate assembly for a file
utils/lib/I2Cdev.cpp.s:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/lib/I2Cdev.cpp.s
.PHONY : utils/lib/I2Cdev.cpp.s

utils/lib/VL53L0X.o: utils/lib/VL53L0X.cpp.o

.PHONY : utils/lib/VL53L0X.o

# target to build an object file
utils/lib/VL53L0X.cpp.o:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/lib/VL53L0X.cpp.o
.PHONY : utils/lib/VL53L0X.cpp.o

utils/lib/VL53L0X.i: utils/lib/VL53L0X.cpp.i

.PHONY : utils/lib/VL53L0X.i

# target to preprocess a source file
utils/lib/VL53L0X.cpp.i:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/lib/VL53L0X.cpp.i
.PHONY : utils/lib/VL53L0X.cpp.i

utils/lib/VL53L0X.s: utils/lib/VL53L0X.cpp.s

.PHONY : utils/lib/VL53L0X.s

# target to generate assembly for a file
utils/lib/VL53L0X.cpp.s:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/utils/lib/VL53L0X.cpp.s
.PHONY : utils/lib/VL53L0X.cpp.s

vision.o: vision.cpp.o

.PHONY : vision.o

# target to build an object file
vision.cpp.o:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/vision.cpp.o
.PHONY : vision.cpp.o

vision.i: vision.cpp.i

.PHONY : vision.i

# target to preprocess a source file
vision.cpp.i:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/vision.cpp.i
.PHONY : vision.cpp.i

vision.s: vision.cpp.s

.PHONY : vision.s

# target to generate assembly for a file
vision.cpp.s:
	$(MAKE) -f CMakeFiles/walle.dir/build.make CMakeFiles/walle.dir/vision.cpp.s
.PHONY : vision.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... walle"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... motor.o"
	@echo "... motor.i"
	@echo "... motor.s"
	@echo "... robot.o"
	@echo "... robot.i"
	@echo "... robot.s"
	@echo "... sensor.o"
	@echo "... sensor.i"
	@echo "... sensor.s"
	@echo "... utils/camera/camera.o"
	@echo "... utils/camera/camera.i"
	@echo "... utils/camera/camera.s"
	@echo "... utils/camera/cameracontrol.o"
	@echo "... utils/camera/cameracontrol.i"
	@echo "... utils/camera/cameracontrol.s"
	@echo "... utils/lib/HMC5883L.o"
	@echo "... utils/lib/HMC5883L.i"
	@echo "... utils/lib/HMC5883L.s"
	@echo "... utils/lib/I2Cdev.o"
	@echo "... utils/lib/I2Cdev.i"
	@echo "... utils/lib/I2Cdev.s"
	@echo "... utils/lib/VL53L0X.o"
	@echo "... utils/lib/VL53L0X.i"
	@echo "... utils/lib/VL53L0X.s"
	@echo "... vision.o"
	@echo "... vision.i"
	@echo "... vision.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

